version: '3.8'

services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app_network
  
  db:
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: menu
      POSTGRES_USER: bd
      POSTGRES_PASSWORD: 262
    ports:
      - "5432:5432"
    networks:
      - app_network
  
  backend1:
    image: durkaepanayal/restaurant:backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', '1')\" &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  backend2:
    image: durkaepanayal/restaurant:backend2
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', '1')\" &&
             python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: overlay
